import type {
  ContextSource,
  DemoTask,
  EvaluationMetric,
  KnowledgeDocument,
  MemoryItem,
  RagEvidence,
  ToolDefinition,
  TraceEvent,
  TraceRun,
} from './types';

export const demoTasks: DemoTask[] = [
  {
    id: 'rag-module',
    title: 'RAG 模块分析',
    subtitle: '观察代码检索、证据注入和报告生成',
    prompt: '分析当前项目的 RAG 模块，并生成一份技术说明。',
    mode: 'react',
    confidence: 0.92,
    route: {
      mode: 'react',
      confidence: 0.92,
      reason: '任务包含多步工程分析和报告生成，需要先定位代码，再读取文件，最后汇总。',
      signals: ['multi_step', 'repo_analysis', 'tool_required'],
      selectedTools: ['search_repo', 'read_file', 'generate_report'],
    },
    plan: {
      goal: '分析当前项目的 RAG 模块，并生成一份技术说明。',
      validationErrors: [],
      steps: [
        {
          id: 'step_1',
          tool: 'search_repo',
          params: { query: 'rag', scope: 'backend' },
          reason: '先搜索项目中与 RAG 检索、文档切分和证据返回相关的文件。',
          dependsOn: [],
        },
        {
          id: 'step_2',
          tool: 'read_file',
          params: { path: 'backend/internal/rag/store.py', lines: 120 },
          reason: '读取核心实现，确认当前是内存文档库和关键词评分。',
          dependsOn: ['step_1'],
        },
        {
          id: 'step_3',
          tool: 'generate_report',
          params: { title: 'RAG 模块技术说明', sections: ['目标', '检索链路', 'Trace 证据'] },
          reason: '把工具结果和检索证据整理成可面试讲解的技术说明。',
          dependsOn: ['step_2'],
        },
      ],
    },
    routeReason: '任务包含多步工程分析和报告生成，需要工具编排。',
    routeSignals: ['multi_step', 'repo_analysis', 'tool_required'],
    steps: [
      'Router 判定为 ReAct 工程任务',
      'Planner 生成 search_repo -> read_file -> generate_report',
      'Executor 顺序调用工具并写入 Trace',
      'Generator 基于工具摘要和 RAG 证据生成回答',
    ],
    toolChain: ['search_repo', 'read_file', 'generate_report'],
    toolCalls: [
      {
        tool: 'search_repo',
        stepId: 'step_1',
        params: { query: 'rag', scope: 'backend' },
        status: 'success',
        durationMs: 240,
        summary: '找到 3 个相关位置：document_store、rag_search、trace.retrieved_docs。',
        output: { matches: ['backend/internal/rag/store.py', 'backend/internal/tools/registry.py', 'backend/main.py'] },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { query: 'rag', scope: 'backend' }, durationMs: 240, summary: '搜索成功', error: null }],
        retryCount: 1,
        riskLevel: 'low',
        recovery: { status: 'completed', strategy: 'none', summary: '首次调用成功，无需恢复。' },
      },
      {
        tool: 'read_file',
        stepId: 'step_2',
        params: { path: 'backend/internal/rag/store.py', lines: 120 },
        status: 'success',
        durationMs: 180,
        summary: '读取内存文档库、段落切分和关键词评分逻辑摘要。',
        output: { path: 'backend/internal/rag/store.py', previewLines: 120 },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { path: 'backend/internal/rag/store.py', lines: 120 }, durationMs: 180, summary: '读取成功', error: null }],
        retryCount: 0,
        riskLevel: 'medium',
        recovery: { status: 'completed', strategy: 'none', summary: '文件读取成功。' },
      },
      {
        tool: 'generate_report',
        stepId: 'step_3',
        params: { title: 'RAG 模块技术说明', sections: ['目标', '检索链路', 'Trace 证据'] },
        status: 'success',
        durationMs: 380,
        summary: '生成 Markdown 技术说明草稿。',
        output: { format: 'markdown', sections: ['目标', '检索链路', 'Trace 证据'] },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { title: 'RAG 模块技术说明', sections: ['目标', '检索链路', 'Trace 证据'] }, durationMs: 380, summary: '报告生成成功', error: null }],
        retryCount: 0,
        riskLevel: 'low',
        recovery: { status: 'completed', strategy: 'none', summary: '报告生成成功。' },
      },
    ],
    answerTitle: 'RAG 模块技术说明',
    answerBullets: [
      '当前 RAG 是轻量内存检索闭环：文档上传后切分为 chunks，并用关键词评分返回 Top-K 证据。',
      'Trace 会记录 retrieved_docs 和 evidence_chain，说明 question -> retrieved chunks -> used context -> answer。',
      'Generator 回答时会明确说明使用了多少条证据和哪些 source。',
      '当前没有接入 Embedding 或向量数据库，演示重点是证据链可观测。',
    ],
    tokenCount: 3214,
    latencyMs: 1842,
    evidenceCount: 3,
  },
  {
    id: 'workflow',
    title: '执行链路解释',
    subtitle: '查看 Router / Planner / Executor 分工',
    prompt: '基于项目结构，说明 Router、Planner、Executor 分别负责什么。',
    mode: 'rag',
    confidence: 0.88,
    route: {
      mode: 'rag',
      confidence: 0.88,
      reason: '问题需要依赖项目文档和模块说明，适合先检索证据再回答。',
      signals: ['knowledge_needed', 'explain_system'],
      selectedTools: ['rag_search'],
    },
    plan: {
      goal: '基于检索证据解释 Router、Planner、Executor 的职责。',
      validationErrors: [],
      steps: [
        {
          id: 'step_1',
          tool: 'rag_search',
          params: { query: 'Router Planner Executor 职责', top_k: 4 },
          reason: '检索架构说明片段，并将证据注入 Generator 上下文。',
          dependsOn: [],
        },
      ],
    },
    routeReason: '问题需要依赖项目文档和模块说明，适合 RAG。',
    routeSignals: ['knowledge_needed', 'explain_system'],
    steps: ['Router 判定为 RAG', 'RAG 检索架构文档', 'Generator 基于证据回答'],
    toolChain: ['rag_search'],
    toolCalls: [
      {
        tool: 'rag_search',
        stepId: 'step_1',
        params: { query: 'Router Planner Executor 职责', top_k: 4 },
        status: 'success',
        durationMs: 260,
        summary: '检索到 4 条架构说明证据。',
        output: { documents: 4 },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { query: 'Router Planner Executor 职责', top_k: 4 }, durationMs: 260, summary: '检索成功', error: null }],
        retryCount: 1,
        riskLevel: 'low',
        recovery: { status: 'completed', strategy: 'none', summary: '检索成功。' },
      },
    ],
    answerTitle: '执行链路说明',
    answerBullets: [
      'Router 负责判断任务进入 chat、rag、tool 还是 react，并记录 reason 和 signals。',
      'Planner 负责把复杂任务转成稳定 JSON Plan，每一步包含工具、参数和依赖。',
      'Executor 负责校验并调用 Tool Registry 中的工具，失败时记录 attempts 和 recovery。',
      'Trace 把 route、plan、tool call、RAG、Memory、Generator 串成可调试视图。',
    ],
    tokenCount: 1980,
    latencyMs: 1260,
    evidenceCount: 4,
  },
  {
    id: 'tests',
    title: '测试失败分析',
    subtitle: '展示失败工具调用和恢复链路',
    prompt: '运行核心测试并总结失败原因。',
    mode: 'tool',
    confidence: 0.9,
    route: {
      mode: 'tool',
      confidence: 0.9,
      reason: '任务需要执行测试并读取失败上下文，属于工程调试型工具调用。',
      signals: ['command_execution', 'failure_analysis'],
      selectedTools: ['run_tests', 'read_file', 'generate_report'],
    },
    plan: {
      goal: '运行核心测试并总结失败原因。',
      validationErrors: [],
      steps: [
        {
          id: 'step_1',
          tool: 'run_tests',
          params: { target: 'core', flags: '-q' },
          reason: '执行核心测试并捕获退出码、stderr 和失败摘要。',
          dependsOn: [],
        },
        {
          id: 'step_2',
          tool: 'read_file',
          params: { path: 'missing.py', lines: 80 },
          reason: '读取失败栈指向的文件；此处故意模拟文件缺失，展示 failed -> stop。',
          dependsOn: ['step_1'],
        },
        {
          id: 'step_3',
          tool: 'generate_report',
          params: { title: '测试失败分析', sections: ['失败摘要', '定位结果', '修复建议'] },
          reason: '汇总测试输出和失败工具调用，生成可解释回答。',
          dependsOn: ['step_2'],
        },
      ],
    },
    routeReason: '任务需要执行测试并读取失败上下文，属于工程调试型工具调用。',
    routeSignals: ['command_execution', 'failure_analysis'],
    steps: ['Router 判定为 Tool / ReAct', 'Planner 生成 run_tests -> read_file -> generate_report', 'Executor 定位 read_file 失败步骤', 'Generator 输出解释性回答'],
    toolChain: ['run_tests', 'read_file', 'generate_report'],
    toolCalls: [
      {
        tool: 'run_tests',
        stepId: 'step_1',
        params: { target: 'core', flags: '-q' },
        status: 'success',
        durationMs: 520,
        summary: '测试适配器执行完成：发现 1 个失败断言。',
        output: { exitCode: 1, stdoutSummary: '9 passed, 1 failed (mock adapter)' },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { target: 'core', flags: '-q' }, durationMs: 520, summary: '测试命令完成，结果包含失败用例', error: null }],
        retryCount: 1,
        riskLevel: 'medium',
        recovery: { status: 'completed', strategy: 'none', summary: '命令完成，后续进入失败分析。' },
      },
      {
        tool: 'read_file',
        stepId: 'step_2',
        params: { path: 'missing.py', lines: 80 },
        status: 'failed',
        durationMs: 95,
        summary: '读取失败：missing.py 不存在，属于不可恢复错误。',
        output: {},
        error: { code: 'file_not_found', message: 'missing.py 不存在，Executor 停止该步骤。' },
        attempts: [{ attempt: 1, status: 'failed', params: { path: 'missing.py', lines: 80 }, durationMs: 95, summary: 'file_not_found，failed -> stop', error: { code: 'file_not_found', message: 'missing.py 不存在。' } }],
        retryCount: 0,
        riskLevel: 'medium',
        recovery: { status: 'stopped', strategy: 'non_recoverable_error', summary: 'failed -> stop，Generator 将解释失败原因。' },
      },
      {
        tool: 'generate_report',
        stepId: 'step_3',
        params: { title: '测试失败分析', sections: ['失败摘要', '定位结果', '修复建议'] },
        status: 'success',
        durationMs: 340,
        summary: '基于测试输出和 read_file 失败生成分析报告。',
        output: { format: 'markdown', sections: ['失败摘要', '定位结果', '修复建议'] },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { title: '测试失败分析', sections: ['失败摘要', '定位结果', '修复建议'] }, durationMs: 340, summary: '报告生成成功', error: null }],
        retryCount: 0,
        riskLevel: 'low',
        recovery: { status: 'completed', strategy: 'explain_failure', summary: '失败信息已进入最终回答。' },
      },
    ],
    answerTitle: '测试失败定位结果',
    answerBullets: [
      'run_tests 已返回测试失败摘要，说明问题来自具体断言而不是执行链路中断。',
      'read_file(missing.py) 触发 file_not_found，Trace 中可以展开该 Tool Call 查看 params、attempt 和 error。',
      'Executor 将不可恢复错误标记为 failed -> stop，并让 Generator 输出解释性回答。',
    ],
    tokenCount: 1740,
    latencyMs: 1520,
    evidenceCount: 0,
  },
];

export const tools: ToolDefinition[] = [
  {
    name: 'search_repo',
    description: '在项目目录中搜索代码、文件名或关键词。',
    params: [
      { name: 'query', type: 'string', description: '搜索关键词', required: true },
      { name: 'scope', type: 'string', description: '限定目录范围', required: false },
    ],
    status: 'available',
    lastCall: '42s ago',
    useCase: '定位 RAG、Agent、Tool Registry 相关代码。',
  },
  {
    name: 'read_file',
    description: '读取指定文件内容并截取关键片段。',
    params: [
      { name: 'path', type: 'string', description: '文件路径', required: true },
      { name: 'lines', type: 'number', description: '读取行数', required: false },
    ],
    status: 'available',
    lastCall: '1m ago',
    useCase: '读取 Planner、Executor、RAG 或测试输出相关文件。',
  },
  {
    name: 'rag_search',
    description: '从轻量内存文档库中检索 Top-K 证据片段。',
    params: [
      { name: 'query', type: 'string', description: '检索问题', required: true },
      { name: 'top_k', type: 'number', description: '返回片段数量', required: false },
    ],
    status: 'available',
    lastCall: '18s ago',
    useCase: '回答需要来源依据的问题。',
  },
  {
    name: 'generate_report',
    description: '根据工具结果和检索证据生成结构化报告摘要。',
    params: [
      { name: 'title', type: 'string', description: '报告标题', required: true },
      { name: 'sections', type: 'array', description: '报告章节', required: false },
    ],
    status: 'available',
    lastCall: '2m ago',
    useCase: '把分析过程沉淀为 Markdown 风格结论。',
  },
  {
    name: 'run_tests',
    description: '执行预设测试目标并返回结构化摘要。',
    params: [
      { name: 'target', type: 'string', description: '测试目标', required: true },
      { name: 'flags', type: 'string', description: '测试参数', required: false },
    ],
    status: 'available',
    lastCall: '5m ago',
    useCase: '演示工具失败、重试和错误定位链路。',
  },
];

export const knowledgeDocs: KnowledgeDocument[] = [
  { id: 'doc-runtime', title: 'Agent Runtime 链路说明', type: 'markdown', chunks: 8, score: 0.91, updatedAt: 'today', preview: 'Router -> Planner -> Executor -> Tools / RAG / Memory -> Generator -> Trace。' },
  { id: 'doc-rag', title: 'RAG Evidence 设计', type: 'markdown', chunks: 6, score: 0.88, updatedAt: 'today', preview: '检索结果返回 content、source、score、metadata，并进入 evidence_chain。' },
  { id: 'doc-memory', title: '轻量 Session Memory', type: 'note', chunks: 4, score: 0.76, updatedAt: 'yesterday', preview: '当前仅保存会话历史、必要摘要和简单偏好。' },
  { id: 'doc-executor', title: 'Executor Recovery Trace', type: 'markdown', chunks: 5, score: 0.82, updatedAt: 'yesterday', preview: '工具失败时记录 attempts、retry_count、risk_level 和 recovery。' },
];

export const ragEvidenceByTask: Record<string, RagEvidence[]> = {
  'rag-module': [
    { source: 'backend/internal/rag/store.py', score: 0.91, content: 'DocumentStore 使用进程内存储保存上传文档，并按段落切分为 chunks。', chunk: 'chunk-1', metadata: { module: 'rag', method: 'keyword' } },
    { source: 'backend/internal/tools/registry.py', score: 0.84, content: 'rag_search 工具返回 content、source、score、metadata，用于前端证据展示。', chunk: 'chunk-2', metadata: { tool: 'rag_search', topK: 3 } },
    { source: 'backend/main.py', score: 0.79, content: 'Trace 会写入 retrieved_docs 和 evidence_chain，Generator 基于 used_context 生成回答。', chunk: 'chunk-3', metadata: { trace: true, stage: 'generator' } },
  ],
  workflow: [
    { source: 'README.md', score: 0.9, content: 'Saber Agent Runtime 的核心链路是 Router、Planner、Executor、Tools/RAG/Memory、Generator、Trace。', chunk: 'chunk-1', metadata: { section: 'Architecture' } },
    { source: 'backend/internal/agent/router.py', score: 0.86, content: 'Router 输出 mode、confidence、reason、signals 和 selected_tools。', chunk: 'chunk-2', metadata: { module: 'router' } },
    { source: 'backend/internal/agent/planner.py', score: 0.82, content: 'Planner 输出包含 goal、steps 和 validation_errors 的 JSON Plan。', chunk: 'chunk-3', metadata: { module: 'planner' } },
    { source: 'backend/internal/executor.py', score: 0.8, content: 'Executor 按步骤调用注册工具，并把 attempts 和 recovery 写入 Trace。', chunk: 'chunk-4', metadata: { module: 'executor' } },
  ],
  tests: [],
};

export const memoryItems: MemoryItem[] = [
  { id: 'mem-1', kind: 'session', title: '当前会话任务', content: '用户正在调试 Saber Agent Runtime 的前后端演示闭环。', source: 'session_history', updatedAt: 'today' },
  { id: 'mem-2', kind: 'summary', title: '历史摘要', content: '项目已完成 Router、Planner、Tool Registry、Trace、RAG Evidence、Memory 和真实联调。', source: 'rolling_summary', updatedAt: 'today' },
  { id: 'mem-3', kind: 'preference', title: '表达偏好', content: 'README 和演示文案使用中文为主，保留关键英文术语。', source: 'explicit_preference', updatedAt: 'today' },
];

export const contextSources: ContextSource[] = [
  { name: '会话历史', detail: '最近多轮 user / assistant 消息，当前真实维护。', active: true },
  { name: '滚动摘要', detail: '必要历史摘要，当前轻量规则生成。', active: true },
  { name: '简单偏好', detail: '显式偏好，当前只做保守提取。', active: true },
  { name: '长期三层记忆', detail: '后续扩展，不作为当前主卖点。', active: false },
];

export const evaluationMetrics: EvaluationMetric[] = [
  { name: '任务成功率', value: 92, unit: '%', trend: 'up', note: 'Demo 任务稳定可复现。' },
  { name: '工具成功率', value: 96, unit: '%', trend: 'up', note: '工具调用结果结构稳定。' },
  { name: 'RAG 命中率', value: 88, unit: '%', trend: 'up', note: '关键词检索证据链稳定。' },
  { name: '平均耗时', value: 4.2, unit: 's', trend: 'down', note: '长任务仍可接受。' },
  { name: '失败任务', value: 3, unit: '', trend: 'flat', note: '失败主要集中在测试分析场景。' },
];

function buildEvidenceChain(task: DemoTask, evidence: RagEvidence[]) {
  const chunks = evidence.map((item, index) => ({
    rank: index + 1,
    usedByGenerator: true,
    score: item.score,
    source: item.source,
    metadata: item.metadata,
    content: item.content ?? item.excerpt ?? '',
  }));
  return {
    question: task.prompt,
    retrievalMethod: 'keyword',
    retrievedChunks: chunks,
    usedContext: chunks.map((chunk) => `[${chunk.rank}] ${chunk.source}: ${chunk.content}`).join('\n\n'),
    answerReference: {
      usedChunkCount: chunks.length,
      sources: chunks.map((chunk) => chunk.source),
      summary: chunks.length ? `Generator 使用 ${chunks.length} 条 keyword 检索证据生成回答。` : 'Generator 未使用 RAG 检索证据。',
    },
  };
}

export function buildTrace(task: DemoTask): TraceRun {
  const evidence = ragEvidenceByTask[task.id] || [];
  const hasToolFailure = task.toolCalls.some((call) => call.status === 'failed');
  const evidenceChain = buildEvidenceChain(task, evidence);
  const events: TraceEvent[] = [
    {
      id: `${task.id}-route`,
      type: 'route',
      title: 'Router',
      detail: `mode=${task.route.mode}, confidence=${Math.round(task.route.confidence * 100) / 100}, reason=${task.route.reason}`,
      status: 'success',
      durationMs: 80,
      meta: { reason: task.route.reason, signals: task.route.signals.join(', ') },
      rawInput: { message: task.prompt },
      outputSummary: task.route.reason,
    },
    {
      id: `${task.id}-plan`,
      type: 'plan',
      title: 'Planner',
      detail: `${task.plan.steps.length} 个 JSON Plan 步骤已生成`,
      status: 'success',
      durationMs: 420,
      meta: { goal: task.plan.goal },
      rawInput: { route: task.route },
      outputSummary: task.plan.goal,
    },
    ...task.toolCalls.map((call, index) => ({
      id: `${task.id}-tool-${index}`,
      type: 'tool_call' as const,
      title: `Tool Call: ${call.tool}`,
      detail: `${call.stepId} / ${call.summary} / params=${JSON.stringify(call.params)}`,
      status: call.status === 'success' ? 'success' as const : 'failed' as const,
      durationMs: call.durationMs,
      meta: { stepId: call.stepId, summary: call.summary },
      rawInput: { params: call.params, attempts: call.attempts, recovery: call.recovery },
      outputSummary: call.summary,
      rawError: call.error,
    })),
    {
      id: `${task.id}-rag`,
      type: 'rag',
      title: 'RAG Retrieval',
      detail: evidence.length ? `question -> ${evidence.length} retrieved chunks -> used context` : '没有检索到证据，Generator 未注入 RAG used context',
      status: evidence.length ? 'success' : 'warning',
      durationMs: 260,
      rawInput: { evidence_chain: evidenceChain },
      outputSummary: evidenceChain.answerReference.summary,
    },
    {
      id: `${task.id}-memory`,
      type: 'memory',
      title: 'Memory',
      detail: '注入轻量会话记忆与本轮任务上下文',
      status: 'success',
      durationMs: 45,
      outputSummary: 'Session history + rolling summary + simple preference',
    },
    {
      id: `${task.id}-gen`,
      type: 'generator',
      title: 'Generator',
      detail: '基于 Route、Plan、Tool Calls、RAG 和 Memory 生成回答',
      status: hasToolFailure ? 'warning' : 'success',
      durationMs: 900,
      rawInput: { evidence_chain: { used_chunk_count: evidence.length, sources: evidence.map((item) => item.source) } },
      outputSummary: task.answerTitle,
    },
    {
      id: `${task.id}-answer`,
      type: 'answer',
      title: 'Answer',
      detail: task.answerTitle,
      status: hasToolFailure ? 'warning' : 'success',
      durationMs: 35,
      outputSummary: task.answerBullets[0],
    },
  ];

  return {
    traceId: `trace-${task.id}`,
    taskId: task.id,
    taskTitle: task.title,
    prompt: task.prompt,
    mode: task.mode,
    confidence: task.confidence,
    route: task.route,
    plan: task.plan,
    status: hasToolFailure ? 'failed' : 'success',
    startedAt: '14:32:21',
    durationMs: task.latencyMs,
    tokenCount: task.tokenCount,
    routeReason: task.routeReason,
    routeSignals: task.routeSignals,
    steps: task.steps,
    toolChain: task.toolChain,
    toolCalls: task.toolCalls,
    events,
    evidence,
    evidenceChain,
    finalAnswerTitle: task.answerTitle,
    finalAnswerBullets: task.answerBullets,
    logs: [
      `[14:32:21] Router -> ${task.route.mode}`,
      `[14:32:22] Planner -> ${task.plan.steps.length} steps`,
      ...task.toolCalls.map((call) => `[14:32:23] Tool -> ${call.tool} ${call.status}`),
      `[14:32:24] RAG -> ${evidence.length} chunks`,
      '[14:32:24] Memory -> 注入轻量上下文',
      `[14:32:24] Generator -> ${hasToolFailure ? '生成失败解释' : '生成回答'}`,
      '[14:32:25] Answer -> 写入 Trace',
    ],
  };
}

export function buildGenericTrace(prompt: string): TraceRun {
  const task = demoTasks[0];
  const trace = buildTrace(task);
  const genericTask: DemoTask = {
    ...task,
    id: 'rag-module',
    title: '自定义任务',
    prompt,
    route: {
      mode: 'react',
      confidence: 0.68,
      reason: 'Mock 适配器仅用于展示结构化 route；真实 /api/chat 会返回同名字段。',
      signals: ['mock', 'demo'],
      selectedTools: [],
    },
    plan: {
      goal: prompt || '自定义任务',
      steps: [
        {
          id: 'step_1',
          tool: 'generate_report',
          params: { title: '模拟响应', sections: ['Route', 'Plan'] },
          reason: 'Mock 模式下展示 Planner JSON schema。',
          dependsOn: [],
        },
      ],
      validationErrors: [],
    },
    toolChain: ['generate_report'],
    toolCalls: [
      {
        tool: 'generate_report',
        stepId: 'step_1',
        params: { title: '模拟响应', sections: ['Route', 'Plan'] },
        status: 'success',
        durationMs: 180,
        summary: 'Mock 模式生成结构化响应摘要。',
        output: { format: 'markdown' },
        error: null,
        attempts: [{ attempt: 1, status: 'success', params: { title: '模拟响应', sections: ['Route', 'Plan'] }, durationMs: 180, summary: '生成成功', error: null }],
        retryCount: 0,
        riskLevel: 'low',
        recovery: { status: 'completed', strategy: 'none', summary: '生成成功。' },
      },
    ],
    evidenceCount: 0,
    answerTitle: '模拟响应',
    answerBullets: ['当前前端处于 Mock 优先模式。', '切换 Real API 后会调用后端 /api/chat 并展示真实 Trace。'],
  };
  const customTrace = buildTrace(genericTask);
  const emptyEvidenceChain = buildEvidenceChain(genericTask, []);
  return {
    ...customTrace,
    traceId: `trace-custom-${Date.now()}`,
    taskId: 'custom',
    taskTitle: prompt || '自定义任务',
    prompt,
    status: 'running',
    evidence: [],
    evidenceChain: emptyEvidenceChain,
    events: customTrace.events.map((event) =>
      event.type === 'rag'
        ? {
            ...event,
            detail: '没有检索到证据，Generator 未注入 RAG used context',
            status: 'warning',
            rawInput: { evidence_chain: emptyEvidenceChain },
            outputSummary: emptyEvidenceChain.answerReference.summary,
          }
        : event,
    ),
    logs: ['[mock] 等待后端接入'],
    startedAt: trace.startedAt,
  };
}
